### ISSUE TITLE
[1.20.1] Crashes on server, Krypton mod missing 

### ISSUE THREAD

**Issue by Kaizuto** [astei/krypton#112]
console says "delete Krypton" but Krypton is not in the mods folder: https://paste.sparked.host/zihenidopa

**Comment by Kaizuto** [comment]
![image](https://github.com/astei/krypton/assets/83712471/7775fd91-9fa5-40ad-a489-3db83017ca91)

**Comment by astei** [comment]
Then why are you filing an issue here?

Took me maybe a minute to Google and discover that this issue raises from the ["PacketFixer"](https://github.com/TonimatasDEV/PacketFixer) mod. Go complain to them.
