### ISSUE TITLE
Request: Backport 0.2.6 to mc1.20.1

### ISSUE THREAD

**Issue by rabbit-time** [astei/krypton#113]
Fixing a memory leak in 0.2.6 is significant and should probably be backported to mc1.20.1 which is currently the most popular modding version for newer versions of Minecraft.

**Comment by astei** [comment]
The memory leak in 0.2.6 that was fixed was in fact a bug _in Krypton_, for a fix to an issue that was actually in Fabric API.

I am not going to "backport" to older versions of Minecraft. I simply do not have the time to do this.

**Comment by astei** [comment]
Also, you can just use an older version of the Fabric API to work around the issue anyway.
