### ISSUE TITLE
Mixin apply for mod krypton failed on login at Minecraft 1.20.5 and Minecraft 1.20.6

### ISSUE THREAD

**Issue by jimchen5209** [astei/krypton#114]
## Affected Minecraft version

- 1.20.5
- 1.20.6

## Mods installed

- Fabric Loader 0.15.10
- Fabric API 0.97.8
- Krypton 0.2.6

## Description

Minecraft has changed the logic of networking (CustomPayload).  
The mod is no longer working on 1.20.5 and 1.20.6 with Fabric API.  
Error thrown on player login without crashing the server.

## Server Log

- [latest.log](https://github.com/astei/krypton/files/15158559/latest.log)

**Comment by astei** [comment]
Just released the 1.20.5 version, let me know if it is working or not. Don't have much time to devote to this mod since my IRL job demands have grown a lot.

**Comment by jimchen5209** [comment]
It's working now. Thank you.
