### ISSUE TITLE
[Server crashed when something about immersive painting mod happened and can't start up again.]

### ISSUE THREAD

**Issue by UnnamedWei** [astei/krypton#121]
[crash-2024-08-18_16.37.32-server.txt](https://github.com/user-attachments/files/16647854/crash-2024-08-18_16.37.32-server.txt)

**Comment by astei** [comment]
This isn't a Krypton issue. The problem is that there's a mod trying to send a very large plugin message and the server is not happy about it.

Also, your server appears to be offline mode and you have a bunch of unsafe mods running.

**Comment by astei** [comment]
Anyway I guess you already reported it to the correct place in Luke100000/ImmersivePaintings#82, and you resolved that issue.

**Comment by UnnamedWei** [comment]
We are still observing this bug, still thank you for responding to this report!!
