### ISSUE TITLE
1.21.1 Support?

### ISSUE THREAD

**Issue by Anvil5465** [astei/krypton#123]
On Modrinth, krypton is listed as only supporting 1.21 and not 1.21.1. Is this correct?

**Comment by flikrheist** [comment]
Yeah im trying to find a 1.21.1 version too :]

**Comment by yuval9313** [comment]
Seems like didn't update yet to 1.21.1, Would love to get the update soon

**Comment by astei** [comment]
Folks, it already works on 1.21.1. You should have just tried it and saw that it works just fine. No changes needed.

**Comment by flikrheist** [comment]
sorry Prism launcher said it only worked on 1.21.

**Comment by flikrheist** [comment]
it didnt work fine

**Comment by astei** [comment]
I tried it and it works fine for me - I can connect to a server just fine.

**Comment by flikrheist** [comment]
No, I mean before you changed the version on Modrinth it didn't work. Now it works.
