### ISSUE TITLE
Incompatibility with SimpleAuth

### ISSUE THREAD

**Issue by MrMrRobat** [astei/krypton#19]
## Versions
- Krypton `0.1.1`
- SimpleAuth `1.7.4`
- Fabric API `0.29.3`

## Description
If [SimpleAuth](https://github.com/samolego/SimpleAuth) is installed, it's impossible to enter the server: you stuck in place (possible that nothing is renderred), chat/commands are not working, `/register` and `/login` commands do nothing

## Steps to reproduce
1. Install Krypton and [SimpleAuth](https://github.com/samolego/SimpleAuth)
2. Try to enter the server while not already logged in (or use `/logout` and reconnect)
3. ~~DOOR STUCK! I BEG YOU!~~ Things described above happen.

## Expected behavior
Krypton doesn't interrupt auth flow of SimpleAuth

## Additional context
Issue in SimpleAuth repo: https://github.com/samolego/SimpleAuth/issues/53

I'm not sure, where it should/can be fixed, but it would be cool to have ability to use Krypton while having beautiful auth system on a server.

**Comment by astei** [comment]
I don't support piracy.

**Comment by astei** [comment]
It's possible [Krypton 0.1.2](https://github.com/astei/krypton/releases/tag/0.1.2) (just released) will fix this issue.

**Comment by MrMrRobat** [comment]
Yes, can't reproduce on 0.1.2! Thanks!
