### ISSUE TITLE
Apparent 3 way mod conflict - Having Krypton on the client while having Cardboard and Fabric API On the server fails to connect to the server (not #9 issue)

### ISSUE THREAD

**Issue by Blobanium** [astei/krypton#20]
so i was having connection issues to my localhost server, finding out that having Krypton on the client while having Cardboard And Fabric API on the server causes connection failure. Krypton on the CLIENT, Not the server (like what happens with #9 it where it crashes the server, this is apparently an entirely different bug)

So When i try to connect with my localhost it says "Failed to connect to the server" with no Trace of logs whatsoever from both the client or server, its doing this every time to connect with this particular mod combination. 

Video of how to reproduce
https://streamable.com/5kmpk6

Something to do with the handshake maybe?

Also The Server doesn't appear to crash in this scenario. unlike in #9 in where it does.

im not entirely sure if it is related to #9 or not.

**Comment by astei** [comment]
We do not support the Cardboard mod and probably never will. I am not interested in seeing which spaghetti pile in there is causing the issue. Closing as "won't fix."
