### ISSUE TITLE
Client issues on latest commit

### ISSUE THREAD

**Issue by Levelowel** [astei/krypton#25]
I never had a problem with Krypton in my mods folder, but I just updated to the latest commit and my client now crashes when I try to enter a world. Another problem I found is that I can't connect to any server.

[crash-report](https://github.com/astei/krypton/files/6494536/crash-2021-05-17_16.35.07-client.txt)
[log](https://github.com/astei/krypton/files/6494540/latest.log)

**Comment by creeper123123321** [comment]
I could reproduce: "Caused by: java.lang.ClassNotFoundException: com.viaversion.fabric.common.handler.PipelineReorderEvent"
