### ISSUE TITLE
Issues with joining some servers.

### ISSUE THREAD

**Issue by popgoesme700** [astei/krypton#32]
While i am not entirely sure if this is a krypton issue or a server issue, but it seems i cant join servers like `play.mcs.gg` and `mccentral.org`, as when trying to join these servers the connection will be lost with krpyton enabled/downloaded.

The servers can be connected fine with my other mods enabled, but krypton just seems to break them.
There may be more servers out there, but these two are the only ones i can find.

This is with krypton version 0.1.2 for 1.16.x (specifically i am using 1.16.5)

**Comment by astei** [comment]
See #22, which also includes a workaround. This is a WONTFIX since it is actually a bug in LilyPad (which those servers use) and not an issue with Krypton.
