### ISSUE TITLE
Krypton is incompatible with Fabric Networking API in 1.17.1 RC 2 

### ISSUE THREAD

**Issue by QPCrummer** [astei/krypton#33]
Here is the crash report: https://pastebin.com/eh0yMbMq

**Comment by astei** [comment]
This is because I have not updated Krypton for 1.17.1 yet.

**Comment by QPCrummer** [comment]
wow, that was a wicked fast response. Ok, it is weird though. It works perfectly fine on a server.

**Comment by astei** [comment]
Will be fixed with #34
