### ISSUE TITLE
Spigot version?

### ISSUE THREAD

**Issue by andreasdc** [astei/krypton#38]
Is it possible to apply your improvements to spigot?

**Comment by astei** [comment]
Not without violating the GPL. Just use Tuinity instead, it has a good portion of the changes in Krypton already and it's the standard for high-performance Minecraft servers.

**Comment by andreasdc** [comment]
> Not without violating the GPL. Just use Tuinity instead, it has a good portion of the changes in Krypton already and it's the standard for high-performance Minecraft servers.

What's gpl? How about 1.8 spigots?

**Comment by astei** [comment]
I am not going to help you with ancient versions of Minecraft.

**Comment by andreasdc** [comment]
> I am not going to help you with ancient versions of Minecraft.

Also I didn't find System.setProperty("io.netty.allocator.maxOrder", "9"); in Velocity.

**Comment by astei** [comment]
It is not relevant. This issue’s main point has been solved.

**Comment by andreasdc** [comment]
> It is not relevant. This issue’s main point has been solved.

Sure but you could answer

**Comment by astei** [comment]
No.
