### ISSUE TITLE
io.netty.allocator.maxOrder

### ISSUE THREAD

**Issue by andreasdc** [astei/krypton#39]
I didn't find System.setProperty("io.netty.allocator.maxOrder", "9"); in Velocity.
Where did you find it? Is it safe to put it in spigot?

**Comment by astei** [comment]
This is irrelevant to the mod. Stop asking for help for your outdated, legally-dubious version of Minecraft.

**Comment by andreasdc** [comment]
> This is irrelevant to the mod. Stop asking for help for your outdated, legally-dubious version of Minecraft.

'Where did you find it?' is releant

**Comment by astei** [comment]
What part of "no" and "stop asking" did you not understand? This is your final warning.

**Comment by astei** [comment]
[Here's your reference.](https://github.com/VelocityPowered/Velocity/blob/c747120b20be1853ee02e7b2b67871249a88aa6d/proxy/src/main/java/com/velocitypowered/proxy/Velocity.java#L38)
