### ISSUE TITLE
[feature request] implement something like "don't send useless entity packets"

### ISSUE THREAD

**Issue by elliots2007** [astei/krypton#41]
Idea to implement something like the “don't send useless entity packets” from purpur

here is the description from purpurs website: 
“Skips sending relative move packets for entities that didn't really move”

this could reduce network usage a lot

**Comment by astei** [comment]
Not inclined to implement this in Krypton, because:

1. No evidence has been provided that this provides any improvement in bandwidth usage.
2. Unknown impact on mods and speedruns.

**Comment by astei** [comment]
Not implementing this. Keep an eye out for other optimizations.
