### ISSUE TITLE
Can't access any singleplayer world

### ISSUE THREAD

**Issue by Levelowel** [astei/krypton#44]
I have no idea what went wrong but I was able to play singleplayer until today. The only thing I did was teleporting back from the end into the overworld by using /execute in minecraft:overworld run tp @s 0 100 0. I remember it stating something like command couldn't be executed in chat but it did in fact teleport me back. The only problem was that nothing was rendering and I couldn't interact with my world. I then decided to close the world and join back in but then got greeted with a message saying: Invalid player data and got shown the multiplayer server selection screen. I tried everything to get back into my world and I can only do that by removing krypton. The weird thing is that I now also can't access any other world because I also get show the same message. Multiplayer is completely fine though and I'm also using the latest build of krypton if that somehow matters.

Here is a log of what's happening every time I try to access a singleplayer world: [2021-08-05-7.log](https://github.com/astei/krypton/files/6939964/2021-08-05-7.log)
The only thing wrong there I can see is this one uuid that causes an ambiguity between arguments in line 46-50. It's also not the uuid of me so I don't know what's going on and it's also the same for any world I want to join.

**Comment by astei** [comment]
Not actually worked, that is a workaround disabling the offending mixin. Reopening.

**Comment by astei** [comment]
Fixed. I didn't realize `ServerWorld` was shared between the client and the server, which meant a required mixin wasn't getting applied. On top of that, Mojang apparently employs the [Pokemon Exception Catching](https://wiki.c2.com/?PokemonExceptionHandling) pattern as well, which made this issue hard to diagnose.
