### ISSUE TITLE
Crash on respawn

### ISSUE THREAD

**Issue by yobson1** [astei/krypton#49]
Krypton version 0.1.5 on both server and client causes the client to crash to desktop upon respawning after death.

**Comment by astei** [comment]
Unable to reproduce, please provide a crash log.

**Comment by yobson1** [comment]
Seems to have been an incompatibility with the graves mod I was using, after uninstalling that and re-installing krypton I can't reproduce it. I expect it was the grave mod to blame as it was also causing chunks to permanently not load.

**Comment by astei** [comment]
Very well then. Closing this issue as not an issue in Krypton.
