### ISSUE TITLE
Download jar

### ISSUE THREAD

**Issue by SirWindfield** [astei/krypton#5]
I can';t find a download on curseforge or other distribution platforms I know about. Do I have to build the mod myself? A git release isn't avaiable as well.

**Comment by astei** [comment]
Answered in the [readme](https://github.com/astei/krypton#compiling--releases). But if you're lazy, I do make [CI builds on the Velocity CI server](https://ci.velocitypowered.com/job/krypton/).

This mod remains a WIP. Not every feature I want to implement in the mod is implemented. In addition I make no guarantees about the stability, especially on non-Linux platforms.

**Comment by SirWindfield** [comment]
I didn't see the notice in thr Readme, sorry! Thanks for helping me out though
