### ISSUE TITLE
Immersive Portals Compatibility

### ISSUE THREAD

**Issue by TofuHell** [astei/krypton#55]
THe mod is incompatible with Immersive portals when krypton is disabled immersive portals works and vice versa, im not sure if you do compatibility updates but much appreciated if do.
____________________________________________________________
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/19/21, 7:02 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3898 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3215.<init>(class_3215.java:89)
	at net.minecraft.class_3218.<init>(class_3218.java:220)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:371)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327)
	at net.minecraft.class_1132.method_3823(class_1132.java:72)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin] from phase [DEFAULT] in config [krypton.mixins.json] from mod [krypton] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_3898::sendChunkDataPackets$beSmart with priority 1000 cannot inject into net/minecraft/class_3898::method_18715(Lnet/minecraft/class_3222;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/class_2818;)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinThreadedAnvilChunkStorage_C with priority 1100 [PREINJECT Applicator Phase -> krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin -> Prepare Injections ->  -> handler$dic000$sendChunkDataPackets$beSmart(Lnet/minecraft/class_3222;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/class_2818;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 387763648 bytes (369 MiB) / 1904214016 bytes (1816 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3950X 16-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9613
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35765.03
	Virtual memory used (MB): 21465.38
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 1428.22
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.0
		adorn: Adorn 3.0.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.5
		amecsapi: Amecs API 1.3.2+mc1.18-pre1
		animal_feeding_trough: Animal Feeding Trough 1.0.2+1.18
		apoli: Apoli 2.2.2
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.4
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.2.51
		aurorasdeco: Aurora's Decorations 1.0.0+1.18
		authme: Auth Me 2.2.0
		awesomedungeon: Awesome Dungeon 1.1.3
		backslot: BackSlot 1.2.3
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.3.0+0
		bcc: BetterCompatibilityChecker 1.0.2
		bclib: BCLib 1.1.1
		beaconoverhaul: Beacon Overhaul 1.5.0+1.18
		beehivetooltips: Beehive Tooltips 1.4.1
		beenfo: Beenfo 1.18-fabric0.43.1-1.3.3
		betterf3: BetterF3 1.2.2
		betterfpsdist: Better FPS distance Mod 1.18-1.3
		betternether: Better Nether 6.0.4
		bettersleeping: BetterSleeping 0.5.1+1.18
		betterthirdperson: Better Third Person 1.5.4
		blockus: Blockus 2.3.3+1.18
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		bountiful: Bountiful 2.0.1
		breakprogress: Break Progress 1.0.1
		calio: Calio 1.4.2
		campchair: Camp Chair 1.0.0
		capybara: Capybara 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.0
		chalk: Chalk 1.2.0
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chat_heads: Chat Heads 0.5.1
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		cleancut: CleanCut 1.18-4.0-fabric
		clickadv: Clickable Advancements Mod 2.1
		clienttweaks: Client Tweaks 7.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.2
		coat: Coat 1.0.0-beta.15
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.0-1.18
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		consistency_plus: Consistency Plus 0.4.2+1.17
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0.4
		cosmetica: Cosmetica 0.3.2
		craftpresence: CraftPresence 1.8.8
		crawl: Crawl 0.10.0
		croptopia: Croptopia 1.7.3
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cspirit: Christmas Spirit 1.1.3-1.18
		dark-enchanting: Dark Enchanting 0.6.2+1.18
		dawn: Dawn API 3.1.0
		deathlog: DeathLog 0.2.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.0
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.4.2
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dungeons_arise: When Dungeons Arise 2.1.49b-fabric
		dynview: Dynamic View Mod 1.18-1.5
		earthtojavamobs: Earth2Java 1.7.4+1.18
		easymagic: Easy Magic 3.2.0
		effective: Effective 1.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.18
		enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1
		enchdesc: EnchantmentDescriptions 9.0.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18
		enhancedcelestials: Enhanced Celestials 2.0.6
		equipmentcompare: Equipment Compare 1.2.9
		experiencebugfix: Experience Bug Fix 18
		extraorigins: Extra Origins 1.18-1
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.8.0+1.18
		fallingtree: FallingTree 2.16.0
		fancymenu: FancyMenu 2.4.3
		fastfurnace: FastFurnace 1.18-4
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fireworkfrenzy: Firework Frenzy 1.7
		forgeconfigapiport: Forge Config API Port 3.1.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.0.2
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.23
		gemsandcrystals: Gems and Crystals Mod Fabric-1.18.1-1.0.1
		geodes: More Geodes 1.2.0
		givemehats: Give Me Hats! 1.7.5
		go-fish: Go Fish 1.4.1-1.18.1
		goblintraders: Goblin Traders 1.4.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.1
		guild: Guild 0.3.6
		heartbond: Heartbond 1.2.0
		highlighter: Highlighter 1.1.2
		hologram-api: Hologram API 0.2.1+1.18-pre5
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		imm_ptl_core: Immersive Portals Core 1.1.4
		immersive_portals: Immersive Portals 1.1.4
		indium: Indium 1.0.2-alpha1+mc1.18
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.4.0-1.18
		inventoryhud: Inventory HUD + 3.4.2
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.2
		krypton: Krypton 0.1.6
		kyrptconfig: Kyrpt Config 1.2.6-1.18
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lavajava: Lava Java 0.2.0
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.6
		lovely_snails: Lovely Snails 1.0.3+1.18
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-more-data: Maybe More Data 1.0.0-1.18
		mcf-reap: MaxVar reap for fabric 1.7.0
		medievalorigins: Medieval Origins 3.0.3
		megane: megane 6.1.1
		megane-base: megane-base 6.1.1
		megane-fabric-transfer: megane-fabric-transfer 6.1.1+1.5.4-b4f4f6cda9
		megane-kibe: megane-kibe 6.1.1+1.9.4-BETA-1.18
		megane-runtime: megane-runtime 6.1.1
		megane-vanilla: megane-vanilla 6.1.1+1.18
		midnightlib: MidnightLib 0.3.1
		milk_plus: Milk+ 1.3.0
		minecraft: Minecraft 1.18.1
		minieffects: Mini Effects 4.0.0
		mm: Manningham Mills 2.3
		morebannerfeatures: More Banner Features 1.1.2
		morerespawnanchors: More Respawn Anchors 1.0.3
		morevillagers-fabric: MoreVillagersFabric 3.0.0-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.18
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		musketmod: Musket Mod 1.4.3
		mythic-mounts: Mythic Mounts 1.18-4.0
		no-telemetry: No Telemetry 1.3.0
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notes: Notes 1.0.9
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.18-1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.3.1
		origins-classes: Origins: Classes 1.2.4
		oxidized: Oxidized 1.5.1
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18.1-61-FABRIC
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		pickupnotifier: Pick Up Notifier 3.1.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		plushies: Plushie Mod 1.1
		polymer: Polymer 0.2.0-beta.8+1.18
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.8+1.18
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.1.1
		q_misc_util: QMiscUtil 1.1.4
		quartzelv: Quartz Elevator 2.0.0+1.18
		quickshulker: Quick Shulker 1.3.1-1.18
		quilt_base: Quilt Base API 1.0.0+1.18-SNAPSHOT
		quilt_block_extensions: Quilt Block Extensions API 1.0.0+1.18-SNAPSHOT
		rad: Reload Audio Driver 1.0.1
		randomblockplacement: RandomBlockPlacement 1.18-fabric0.43.1-1.1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.18-1
		repurposed_structures: Repurposed Structures 3.1.10+1.18.1
		rocks: This Rocks! 1.5.2
		rotten: FleshZ 1.4.4
		roughlyenoughitems: Roughly Enough Items 7.0.352
		satin: Satin 1.7.0
		sculk_worm: Sculk Worm 0.1.2
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		simple_backpack: SimpleBackpack 1.2.26
		skinlayers: 3d Skin Layers 1.3.1
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0_b0.1.8
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		thonkutil: ThonkUtil 2.2.1+1.18
		thonkutil-base: ThonkUtil Base 1.1.0+d5f23f2ac8
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.1+f101d003c8
		thonkutil-legacy: ThonkUtil Legacy 1.0.2+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.2.0+e4c51c01c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.0+769eee82c8
		tinyskeletons: Tiny Skeletons 3.1.0
		toms_storage: Tom's Simple Storage Mod 1.1.19
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torchbowmod: TorchBowMod 1.0
		tradingpost: Trading Post 3.1.0
		trashslot: TrashSlot 11.0.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		twigs: Twigs 1.1.2
		twm: The Wild Mod 0.2
		universal-graves: Universal Graves 1.2.2+1.18
		universal_ores: Universal Ores 1.2.0
		unvotedandshelved: Unvoted & Shelved 1.0.4
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.18
		urns: Urns 1.0.1
		veinmining: Vein Mining 0.0.11-1.18
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.2
		visuality: Visuality 0.3.3
		visualworkbench: Visual Workbench 3.1.0
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		wandering_collector: Wandering Collector 1.0.3+mc1.18-rc3
		waystones: Waystones 2.3.4
		wmitaf: WMITAF 2.2.0
		wthit: wthit 4.3.1
		xaerominimap: Xaero's Minimap 21.22.3.1
		xaeroworldmap: Xaero's World Map 1.18.6.1
		xlpackets: XLPackets 2.1-1.17.1
		xp_storage: XP Storage 1.4.3+1.18
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.18
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, aurorasdeco:pack/runtime, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by astei** [comment]
I give in. There's now been at least 5 complaints about this.

It's fixed in b251fa0, see also qouteall/ImmersivePortalsMod#833
