### ISSUE TITLE
Crash with Immersive Portals

### ISSUE THREAD

**Issue by efffauw** [astei/krypton#58]
Immersive portals crashes with Krypton upon entering a world

Fabric loader 0.12.12
immersive-portals-1.1.7-mc1.18.1
krypton-0.1.6

[crash](https://pastebin.com/cshc5Pyq)

[Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod)

**Comment by astei** [comment]
Already fixed, will be released in a future version of Krypton
