### ISSUE TITLE
Krypton 0.1.8 causes a disconnect when trying to connect to any server running Krypton

### ISSUE THREAD

**Issue by Justsnoopy30** [astei/krypton#64]
All I see is 
![image](https://user-images.githubusercontent.com/33374736/157377414-8fb54014-4a8a-4ae6-b4dc-c05e75b14d33.png)

and 
`[23:12:28] [Server thread/INFO]: Justsnoopy30 lost connection: Disconnected
[23:12:28] [Server thread/INFO]: Justsnoopy30§r left the game
[23:12:28] [Server thread/WARN]: handleDisconnection() called twice`
in the server console. This did not happen on Krypton 0.1.7.

**Comment by astei** [comment]
Fixed
