### ISSUE TITLE
Krypton failing to send packets 1.18.2

### ISSUE THREAD

**Issue by QPCrummer** [astei/krypton#65]
- Krypton 1.7 (and 1.9)
- MC 1.18.2

Logs: https://pastebin.com/etf5JJGJ

The issue is basically only people that have Krypton 1.9 can join the server, but I have some users on my server that don't use fabric.

**Comment by astei** [comment]
Unable to reproduce this issue

**Comment by QPCrummer** [comment]
Hmm, interesting. I think our internet went out while launching. Fairly sure that is the reason. I’ll close this as Krypton 1.9 was working earlier. Sorry for bothering you.
