### ISSUE TITLE
Crash on World Generation

### ISSUE THREAD

**Issue by TheAyes** [astei/krypton#68]
So... This one is a pretty weird one. I myself do not understand what's happening at all.
Following scenario:
I'm using the Quilt Modloader with Krypton and Lithium -> The Game crashes on world gen.
However using these 2 mods with a bunch of other Client Side mods does work perfectly fine.
I am not sure which mod exactly is causing the crash to not happen. But apparently there's one.

Mod list for the working version:
Cloth Config
CCM
Continuity
Cull Leaves
DashLoader
DynamicFPS
EnahancedBlockEntities
Falling Leaves
Indium
Iris
Krypton
LambDynamicLights
LazyDFU
Lithium
Mod Menu
Phosphor
Presence Footsteps
QSL
Reese's Sodium Options
Sodium
Sodium Extras

Modlist for the non working version:
Lithium
Krypton
QSL

Crash Log:
https://paste.ee/p/OqSGL

**Comment by NoComment1105** [comment]
This is caused by quilt loader not ready custom values in the fabric.mod.json properly, this is a known bug and can be worked around by adding
 ```properties
mixin.alloc.entity_tracker=false
```
to the `lithium.properties` config file
