### ISSUE TITLE
Send chunks closest to player first

### ISSUE THREAD

**Issue by solonovamax** [astei/krypton#69]
Currently, krypton iterates through chunks and begins sending chunks to the player beginning in the negative x and negative z corner, then moving along the z axis, before wrapping up to the x.
The pattern in which the chunks are sent to the client is illustrated here, where the green dot is the player and the red numbers are the order the chunks load in:
<img src="https://user-images.githubusercontent.com/46940694/167670220-80c04552-52cb-446a-9b91-9a20a3da9738.png" width="400px"/>

The cause for this can be found in the [`ThreadedAnvilChunkStorageMixin` class, in the method `updatePosition`](https://github.com/astei/krypton/blob/master/src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java#L112-L124).

This causes the further chunks from the player to be sent first, which feels as if the server is performing slowly for high ping players. Thus, players with a slow connection will perceive servers with krypton as performing *worse* than those without. Further, this breaks vanilla behaviour, as vanilla minecraft sends chunks closest to the player first.

---

It would be much better if the closest chunks were the ones that were sent first, as shown in this illustration here:
<img src="https://user-images.githubusercontent.com/46940694/167670550-3949d9ca-f1c9-49eb-b770-98784956ec74.png" width="400px"/>

Thus allowing for slower clients to begin playing without having to wait for roughly half of the chunks to be sent.

**Comment by Kichura** [comment]
Can confirm this on my own linux machine here as the chunks would always begin rendering from the right of 0 degrees instead of the suggestion below - wonder what astei can pull off with this.
