### ISSUE TITLE
Add libdeflate?

### ISSUE THREAD

**Issue by andreasdc** [astei/krypton#72]
Hey, I noticed that in logs:
Compression will use Java 11, encryption will use Java
Why can't we use libdeflate in the client?

**Comment by astei** [comment]
Because it's only supported on Linux and I have no appetite to support other OSes

**Comment by andreasdc** [comment]
> Because it's only supported on Linux and I have no appetite to support other OSes

That would be really nice, if there's not much work I would love to see it. :)
