### ISSUE TITLE
Multiconnect compatibility

### ISSUE THREAD

**Issue by Felix14-v2** [astei/krypton#80]
**Description**
When using Multiconnect together with Krypton, sending too long messages to the chat leads to disconnection from the server with the error "The string is too big": https://youtu.be/vSiVAoM5Hew

**Additional**
[Multiconnect#376](https://github.com/Earthcomputer/multiconnect/issues/376)
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8921936/latest.log)

**Comment by creeper123123321** [comment]
https://github.com/astei/krypton/blob/master/src/main/java/me/steinborn/krypton/mixin/shared/network/microopt/PacketByteBufMixin.java#L44
Vanilla uses the amount of UTF-16 char (2 bytes) used by string, not the UTF-8 byte amount

**Comment by creeper123123321** [comment]
Also probably it happens without multiconnect

**Comment by astei** [comment]
Well, then I've goofed up big time and didn't even notice. I'll fix this.

**Comment by astei** [comment]
Fixed with 8d957c904f8a1f8ae46f3f792ce6f9b800338bb2
