### ISSUE TITLE
Will it affect single player?

### ISSUE THREAD

**Issue by ardissaps** [astei/krypton#81]
Do I need it if I don't play multiplayer?

**Comment by Kichura** [comment]
You can keep it for singleplayer if you want to maintain your smooth experience, otherwise that is up to you.

**Comment by ardissaps** [comment]
> smooth experience

Which smooth experience? Do it fix that sometime my skin does not load?

**Comment by ardissaps** [comment]
@astei

**Comment by ardissaps** [comment]
> You can keep it for singleplayer if you want to maintain your smooth experience, otherwise that is up to you.

Can you explain it how it help with single player?

**Comment by astei** [comment]
There are some changes in Krypton that could marginally improve the single player experience. If you are sharing the world with other players, Krypton can optimize the connection on your end.

Otherwise, Krypton may not be very useful to you.
