### ISSUE TITLE
Krypton does not support 1.19.1.

### ISSUE THREAD

**Issue by Kichura** [astei/krypton#84]
Starting up the game with krypton enabled will cause the game to [crash](https://pastebin.com/raw/pbCXXcME).

**Comment by astei** [comment]
Unsurprising since 1.19.1 just came out and I have had no time to update the mod

**Comment by macbrayne** [comment]
For what it's worth, I get a different crash: [Gist](https://gist.github.com/macbrayne/7996e4024844d8bbff3d87aa47bb0dd1)
