### ISSUE TITLE
Mark 1.19.1 version as 1.19.2 compatible

### ISSUE THREAD

**Issue by PinkGoosik** [astei/krypton#89]

**Comment by Kichura** [comment]
Not a requirement since 1.19.2 shares the same protocol as 1.19.1,
As for the dependency; it is 1.19.x meaning any minor versions of 1.19 are accepted.

**Comment by PinkGoosik** [comment]
I mean curseforge/modrinth versions😅, some mod managers don't detect krypton as compatible mod

**Comment by xVANKO** [comment]
> I mean curseforge/modrinth versions😅, some mod managers don't detect krypton as compatible mod

Indeed - i.e. **Ferium**

**Comment by imsofi** [comment]
This also includes packwiz.

**Comment by astei** [comment]
Fixed this some time ago. Also unfeatured the Krypton 0.2.0 release on Modrinth since it's tripping up people.
