### ISSUE TITLE
Conflict With Bukkit4Fabric - Server Crash When A Client Tries to Interact with the server

### ISSUE THREAD

**Issue by Blobanium** [astei/krypton#9]
Hi So the server crashes when a client attempts to interact with the server

Managed it to narrow it down seems that bukkit4fabric is the issue, I Removed all the server plugins also but that didnt seem to fix the issue

Mods folder
![Capture](https://user-images.githubusercontent.com/45613796/102527548-17756e80-4052-11eb-9066-f38710790203.PNG)

Crash log
[crash-2020-12-17_10.21.37-server.txt](https://github.com/astei/krypton/files/5711425/crash-2020-12-17_10.21.37-server.txt)

Video showing how to reproduce
https://streamable.com/xdodl1
 It seems to also trigger a server crash when you try to connect to the server also

tell me if there's anything else i need thanks

**Comment by astei** [comment]
Bukkit4Fabric uses `@Overwrite` to [override the handling of the encryption key exchange](https://github.com/BukkitFabric/bukkit4fabric/blob/master/src/main/java/com/javazilla/bukkitfabric/mixin/network/MixinServerLoginNetworkHandler.java#L87) that Krypton [mixes into](https://github.com/astei/krypton/blob/master/src/main/java/me/steinborn/krypton/mixin/network/shared/pipeline/encryption/ServerLoginNetworkHandlerMixin.java#L26).

This problem cannot be solved in Krypton, please file a bug with Bukkit4Fabric.
