### ISSUE TITLE
Crash on loading game

### ISSUE THREAD

**Issue by OsoaGH** [astei/krypton#90]
Using Quilt 1.19.2. [Here](https://pastebin.com/xaDbTnZb) is the log.

**Comment by AntyMew** [comment]
Reproduced with minimum mod list of Quilt Standard Libraries and Krypton. Works without QSL installed

**Comment by astei** [comment]
You're not running the correct version of Krypton - 0.2.1 is the release that's compatible with 1.19.2. The log shows Krypton 0.2.0.

**Comment by astei** [comment]
I unfeatured the Krypton 0.2.0 release on Modrinth since that's probably where you grabbed 0.2.0. 0.2.1 is now correctly featured.
