### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by duronald** [astei/krypton#96]
Does not work with 1.19.4. Crashes when you attempt to connect.

**Comment by astei** [comment]
Unsurprisingly, this is because Krypton needed to be updated, and the update PR (#95) was merged hours ago, and I have not yet cut a new release.

Please be patient.

**Comment by duronald** [comment]
Oops. Sorry about that, I did not see the pull request.

**Comment by astei** [comment]
0.2.2 is now released, and works with 1.19.4.
