### ISSUE TITLE
[1.19.2] watchdog crash / Krypton + RoughlyEnoughResources conflict

### ISSUE THREAD

**Issue by itsdinkd** [astei/krypton#99]
https://gist.github.com/itsdinkd/3f36fba94e021c86e7c1e2d79160d10f

Crashing official AQM2, unable to reproduce unfortunately, its random.

**Comment by astei** [comment]
I can't see how Krypton is connected here - in fact, I bet this would happen even without Krypton.

In general, when you add 600 mods and press "blend", don't be shocked when the server chokes under the mess of mixins and extra logic it is forced to run.

Have you narrowed it down to exactly Krypton and RoughlyEnoughResources? Given the balance of things, I'd rather blame RoughlyEnoughResources for trying to serialize what is presumably a giant blob of JSON _in the main thread_.

**Comment by itsdinkd** [comment]
>In general, when you add 600 mods and press "blend", don't be shocked when the server chokes under the mess of mixins and extra logic it is forced to run.
🙄 400* and its been fine for the 2 years I've had this modpack running each mc version with 300+ mods. Only until 1.192 have I had watchdog issues.

As mentioned _**unable to reproduce unfortunately, its random**_ so no. i haven't. I'm going off the stacktrace. but you are probably right on RER being the cause. this isn't the first RER incompatible issue.

**Comment by astei** [comment]
> 🙄 400*

I was just estimating based on the line count in the crash report, which probably includes side-loaded mods
